### ISSUE TITLE
Historical API

### ISSUE THREAD

**Issue by CBVTorrijos** [aws-samples/aws-serverless-connect-wallboard#10]
Hello,

It seems that when adding historical API, the wallboard does not display what is on connect wallboard. HTML wallboard just shows 0 while connect wallboard shows numbers. It seems as if it's not picking up the correct information. Any idea?

**Comment by Brettles** [comment]
I would check to see that the Lambda function for GetHistoricalMetrics is running and doesn't have an error - you should see logs in CloudWatch Logs for that.

Otherwise: Any particular historical metric that isn't working? If there is a specific one (or two/three) it's easier to track down.

**Comment by CBVTorrijos** [comment]
Thank you! your recommendation was spot on!
