### ISSUE TITLE
SAML Authenication Not Working

### ISSUE THREAD

**Issue by bmurrell-cbre** [aws-samples/aws-serverless-connect-wallboard#12]
Hello,

I was able to deploy the agent status wallboard without any issues using CONNECT_MANAGED however whenever I try to use this wallboard with an instance that uses SAML authentication it doesn't populate agent status for our users. Does this wallboard work with SAML instances?

**Comment by Brettles** [comment]
While I haven't tried it with a SAML-authenticated connect instance I don't think that should affect how the wallboard works. The components of interest are the Lambda functions and they are authorised using IAM roles. So as long as the Lambda functions have permissions to read/write the DynamoDB table; to receive data from the Kinesis Data Stream (for agent status updates); and to query the Connect APIs - then it should all work as normal.

AFAIK SAML authentication is for agents/supervisors/managers, not for the programmatic access to the Connect APIs that are used to gather statistics (historical and real-time metrics).
