### ISSUE TITLE
Yaml Failed to create stack

### ISSUE THREAD

**Issue by AkhirHassan** [aws-samples/aws-serverless-connect-wallboard#13]
The Yaml File on this repository is failing to launch the stack in AWS CloudFormation.
<img width="635" alt="Screenshot 2023-02-28 142146" src="https://user-images.githubusercontent.com/107675199/221745223-e8d6be65-799b-4679-b4d7-1d9307b46875.png">

**Comment by Brettles** [comment]
Thanks for letting me know - could you tell me what the error message is at the bottom-right of the screen and what resource it applies to? I think that's the source of the problem but it's cut off at the end.

**Comment by AkhirHassan** [comment]
Hi Brett,

The Logical ID is LambdaAgentSourceMapping and the Status Reason is   Resource
handler returned message: "Model validation failed (#/EventSourceArn: 2
schema violations found) #/EventSourceArn: expected minLength: 12, actual:
9 (#/EventSourceArn) #/EventSourceArn: failed validation constraint for
keyword [pattern] (#/EventSourceArn)" (RequestToken:
88866a11-bdbd-4227-299d-cdc8b00e0b95, HandlerErrorCode: InvalidRequest)

Thank you
Regards
Abdul Hassan

**Comment by Brettles** [comment]
When you created the stack what did you enter for the "KinesisAgentStream" ARN? It looks like that may not have been in the right format. It should be "arn:aws:kinesis:REGION-NAME:ACCOUNT-NAME:stream/STREAM-NAME" and the stream must exist before creating the stack.

**Comment by AkhirHassan** [comment]
its working Fine now
Thank you for your help
regards
Abdul
