### ISSUE TITLE
Styling of Table

### ISSUE THREAD

**Issue by Aikleong7** [aws-samples/aws-serverless-connect-wallboard#17]
Hi, I would like to change the font family for the table where i tried different way of styling, in file styling. it does not apply to the table itself. how do I style the table?

**Comment by Brettles** [comment]
The short answer is that it is all in the stylesheet that you define in your HTML.

The longer answer is that you can apply styles to the whole wallboard table or to individual cells as you need to.

If you look at the raw HTML that is returned to the caller you'll see a few things:

- The class for for the table is `wallboard-<wallboardname>` so if your wallbaord is called "main" then that class will be `wallboard-main`.
- The class for each call is `RxCy` - row X, column Y.

It's probably easiest to apply a style to the whole table. In your stylesheet you can do something like:
```css
table.wallboard-main {
 font-family: sans-serif;
 font-size: 16px;
}
```

Note that you can change the font, font size and font colour in the wallboard configuration file as described in the README - look in the "Wallboard Configuration" section and then under "Defaults". Each cell can also be individually changed as well.
