### ISSUE TITLE
Type in wallboard definition example

### ISSUE THREAD

**Issue by ptegan** [aws-samples/aws-serverless-connect-wallboard#2]
Not a biggie but in the example wallboard definition example shown in the [blog](https://aws.amazon.com/blogs/contact-center/building-a-serverless-contact-center-wallboard-for-amazon-connect/) there is a space between the colon and the yyyyyyyyy for the Contacts_Handled line which results in a 'mapping values are not allowed here' as the space indicates that it is (incorrectly) a key:value pair.

Reference: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy:CONTACTS_HANDLED

Removing the space to make it looks like xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy recolves the issue :)

**Comment by Brettles** [comment]
Nice find! Thanks! Will try and get that typo changed out.
