### ISSUE TITLE
GetMetricData SERVICE_LEVEL requires additional parameter

### ISSUE THREAD

**Issue by eaagastr** [aws-samples/aws-serverless-connect-wallboard#7]
1. Issue can be reproduced when using a Source that queries service level:
```
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy:SERVICE_LEVEL
```

2. See CloudWatch log error, from get-historical-metrics.py / ConnectWallboard-Historical-Metrics Lambda:

```
[ERROR]	2022-02-17T22:20:13.482Z	522c18e7-9f30-4a7b-9dd4-ecee71fd3d4e	
Failed to get historical data: An error occurred (InvalidParameterException) when calling the GetMetricData operation: 
You must specify a Threshold when you retrieve SERVICE_LEVEL metrics.
```
3. See CloudTrail API log with the same Invalid Parameter exception:

```
	"requestParameters": {
		"HistoricalMetrics": [
			{
				"Name": "SERVICE_LEVEL",
				"Unit": "PERCENT",
				"Statistic": "AVG"
			}
		],
		"Filters": {
			"Queues": [
				"61d3e946-1e58-4ecb-a96a-7b4a13846852"
			]
		},
		"EndTime": 1645136400,
		"InstanceId": "403a015e-1fca-4db8-a1af-583baedba546",
		"Groupings": [
			"QUEUE"
		],
		"StartTime": 1645056000
	},
	"responseElements": {
		"Message": "You must specify a Threshold when you retrieve SERVICE_LEVEL metrics."
	},
```
4. We can see in get-historical-metrics.py / ConnectWallboard-Historical-Metrics Lambda that MetricUnitMapping does not handle the needed params for SERVICE_LEVEL.

5. See here for expected format for SERVICE_LEVEL API call. Note this is the only metric from GetMetricData that requires the additional Threshold parameter, so it is likely all other metrics work currently, except for SL. 

https://docs.aws.amazon.com/connect/latest/APIReference/API_GetMetricData.html#API_GetMetricData_Examples

```
      {
         "Name" : "SERVICE_LEVEL",
         "Threshold" : {
            "Comparison" : "LT",
            "ThresholdValue" : 30.0
         },
         "Unit" : "PERCENT",
         "Statistic" : "AVG"
      }
```
```
SERVICE_LEVEL

    You can include up to 20 SERVICE_LEVEL metrics in a request.

    Unit: PERCENT

    Statistic: AVG

    Threshold: For ThresholdValue, enter any whole number from 1 to 604800 (inclusive), in seconds. For Comparison, you must enter LT (for "Less than").
```

6. Is it possible to modify the solution/Lambda to accept SL X as a value, where X is the time in queue before being the interaction is answered? Or otherwise handle this Invalid Parameter Exception when using SERVICE_LEVEL. 

Currently, surfacing service level metrics in the yaml template will cause the Lambda to throw errors and will not update the DDB with up to date metric data (and the rendered wallboard website won't either).

Thank you!

**Comment by Brettles** [comment]
Good point - did not realise that; and it looks like SERVICE_LEVEL is the only metric which currently needs "special" handling.

I've added some code to quickly handle this for you - let me know how it goes. There is a note in the README.md which talks to what I've done (search for SERVICE_LEVEL - you'll find it).

**Comment by eaagastr** [comment]
Confirming the hardcoded ServiceLevelThreshhold works, no errors thrown, metric data updates as expected.

Only caveat is the same SL X value will apply across all queues/wallboards.

Thank you for the fast turnaround! Will close this now.
