### ISSUE TITLE
Not able to deploy in Singapore region

### ISSUE THREAD

**Issue by bnirwan** [aws-samples/aws-serverless-connect-wallboard#8]
It gives bucket access error. Can you please do the needful to deploy the cloudformation in singapore region also. Thanks.

**Comment by bnirwan** [comment]
Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for connectwallboard-ap-southeast-1/get-historical-metrics.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: a334e2a0-f074-4abe-8e91-21e3b92a31e9)" (RequestToken: c034751a-4f58-ce00-9c8e-db607ef25c5f, HandlerErrorCode: AccessDenied)

**Comment by Brettles** [comment]
Please test again now - I've uploaded the code to ap-southeast-1.

**Comment by bnirwan** [comment]
Still this -
Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for connectwallboard-ap-southeast-1/process-agent-event.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: 27894044-b035-4cd2-b0e4-9ad9f824b67d)" (RequestToken: aee3a5f7-91c1-39de-96ab-cddc0ce06258, HandlerErrorCode: AccessDenied

**Comment by bnirwan** [comment]
Yesterday it said historic today agent events zip. Did u uploaded all required code. Can u pls check. Thanks

**Comment by Brettles** [comment]
Apologies. Multiple changes in flight. Please grab a copy of the updated CloudFormation template: https://github.com/aws-samples/aws-serverless-connect-wallboard/blob/master/wallboard-cfn.yaml

What you should see is that the lines that start with "S3Bucket" (which is where the Lambda code is located) now say "cfn-code".

**Comment by bnirwan** [comment]
Thanks. It worked. I really appreciate the quick solution.
